name: CI - payment-provider
on:
  push:
    branches: [feat-ano-code-challenge]
    paths:
      - "payment-provider/**"
      - ".github/workflows/build-and-push-payment-provider.yaml"

jobs:
  build_push_image:
    uses: ./.github/workflows/push-to-dockerhub.yaml
    with:
      app_name: payment-provider
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_access_token: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
